import 'package:flutter/widgets.dart';

/// Core types for the Flutter AI SDK.

// ─── Agent Modes ──────────────────────────────────────────────

enum AgentMode { text, voice }

// ─── Provider Names ──────────────────────────────────────────

enum AiProviderName { gemini, openai }

// ─── Interactive Element (discovered from Element tree) ─────────

enum ElementType {
  pressable,
  textInput,
  switchToggle,
  scrollable,
  slider,
  picker,
  datePicker,
  checkbox,
  text,
}

enum AiPriority {
  high,
  low,
}

/// Represents an interactive widget discovered on the screen.
class InteractiveElement {
  /// Unique index assigned during tree walk
  final int index;

  /// Element type (e.g. pressable, textInput)
  final ElementType type;

  /// Human-readable label (extracted from Text children or semantics)
  final String label;

  /// Declarative AI priority explicitly set by the developer
  final AiPriority? aiPriority;

  /// The nearest enclosing AiZone ID (if any)
  final String? zoneId;

  /// Reference to the Flutter Element for execution (nullable when semantics-based)
  final Element? element;

  /// SemanticsNode ID — used to dispatch SemanticsAction.tap instead of direct callback
  final int? semanticsNodeId;

  /// Key-value pairs for state/properties (e.g. checked, value, enabled)
  final Map<String, dynamic> properties;

  InteractiveElement({
    required this.index,
    required this.type,
    required this.label,
    this.aiPriority,
    this.zoneId,
    this.element,
    this.semanticsNodeId,
    this.properties = const {},
  });
}

// ─── Dehydrated Screen State ──────────────────────────────────

class DehydratedScreen {
  /// Current screen name (from routing state)
  final String screenName;

  /// All available screen names
  final List<String> availableScreens;

  /// Indexed interactive elements as text for the LLM prompt
  final String elementsText;

  /// Raw elements list for tool resolution
  final List<InteractiveElement> elements;

  DehydratedScreen({
    required this.screenName,
    required this.availableScreens,
    required this.elementsText,
    required this.elements,
  });
}

// ─── Screen Map (generated by CLI) ───────────────────────────

class ScreenMapEntry {
  final String? title;
  final String description;
  final List<String>? navigatesTo;

  ScreenMapEntry({
    this.title,
    required this.description,
    this.navigatesTo,
  });

  factory ScreenMapEntry.fromJson(Map<String, dynamic> json) {
    return ScreenMapEntry(
      title: json['title'] as String?,
      description: json['description'] as String? ?? 'Screen content',
      navigatesTo: (json['navigatesTo'] as List?)?.cast<String>(),
    );
  }
}

class ScreenMap {
  final String generatedAt;
  final String framework;
  final Map<String, ScreenMapEntry> screens;
  final List<List<String>> chains;

  ScreenMap({
    required this.generatedAt,
    required this.framework,
    required this.screens,
    required this.chains,
  });

  factory ScreenMap.fromJson(Map<String, dynamic> json) {
    var screensMap = <String, ScreenMapEntry>{};
    if (json['screens'] != null) {
      final screensObj = json['screens'] as Map<String, dynamic>;
      for (final key in screensObj.keys) {
        screensMap[key] = ScreenMapEntry.fromJson(screensObj[key]);
      }
    }

    var chainsList = <List<String>>[];
    if (json['chains'] != null) {
      chainsList = (json['chains'] as List)
          .map((e) => (e as List).cast<String>())
          .toList();
    }

    return ScreenMap(
      generatedAt: json['generatedAt'] as String? ?? '',
      framework: json['framework'] as String? ?? 'go_router',
      screens: screensMap,
      chains: chainsList,
    );
  }
}

// ─── Agent Execution & Configuration ──────────────────────────

class AgentReasoning {
  final String currentScreen;
  final String observation;
  final String? activeZone;
  final String goal;
  final String plan;
  final String? previousGoalEval;
  final String? memory;

  AgentReasoning({
    this.currentScreen = '',
    this.observation = '',
    this.activeZone,
    this.goal = '',
    this.plan = '',
    this.previousGoalEval,
    this.memory,
  });
}

class AgentStep {
  final int stepIndex;
  final AgentReasoning? reasoning;
  final String actionName;
  final Map<String, dynamic> actionParams;
  String? result;
  String? error;

  AgentStep({
    this.stepIndex = 0,
    this.reasoning,
    required this.actionName,
    required this.actionParams,
    this.result,
    this.error,
  });
}

class AgentAction {
  final String name;
  final Map<String, dynamic> input;
  final String output;

  AgentAction({
    required this.name,
    required this.input,
    required this.output,
  });
}

class ExecutionResult {
  final bool success;
  final String message;
  final List<AgentStep> steps;

  ExecutionResult({
    required this.success,
    required this.message,
    this.steps = const [],
  });
}

enum McpServerMode { auto, enabled, disabled }

class AgentConfig {
  /// Which LLM provider to use for text mode (default: gemini).
  final AiProviderName provider;

  /// API key (for prototyping only).
  final String? apiKey;

  /// The URL of your secure backend proxy (for production).
  final String? proxyUrl;

  /// Optional headers to send to your proxyUrl.
  final Map<String, String>? proxyHeaders;

  /// The model to use.
  final String? model;

  /// Maximum steps per task (default: 15).
  final int maxSteps;

  /// MCP server mode.
  final McpServerMode mcpServerMode;

  /// Elements the AI must NOT interact with.
  final List<GlobalKey>? interactiveBlacklist;

  /// If set, the AI can ONLY interact with these elements.
  final List<GlobalKey>? interactiveWhitelist;

  /// Automatically trigger errors if the app handles them gracefully (default: true).
  final bool reportErrorsAsExceptions;

  /// Extra time to wait after navigation/interaction before reading the tree.
  final Duration gracePeriod;

  // Lifecycle Callbacks
  final Future<void> Function(int stepCount)? onBeforeStep;
  final Future<void> Function(List<AgentStep> history)? onAfterStep;
  final Future<void> Function(ExecutionResult result)? onFinish;
  final Future<void> Function(Object error, ExecutionResult partialResult)? onError;
  
  /// Callback for agent thinking status
  final void Function(String message)? onStatusUpdate;

  // Instructions & Context
  final String? language;
  final String? instructions;
  final String? systemPromptSuffix;
  final String? toolInstructions;

  /// The pre-generated screen map containing routes and descriptions.
  final ScreenMap? screenMap;

  // Budget Guards
  final int? maxTokenBudget;
  final double? maxCostUsd;
  final void Function(TokenUsage usage, double estimatedCost)? onBudgetWarning;

  /// Allow the agent to interact with UI (default: true).
  final bool enableUiControl;

  /// Transform screen content before the LLM sees it.
  /// Use to mask PII, credit card numbers, passwords, or any sensitive data.
  /// Mirrors react-native-agentic-ai's `transformScreenContent` prop.
  /// Example: (content) async => content.replaceAll(cardNumberRegex, '****')
  final Future<String> Function(String content)? transformScreenContent;

  /// Router instance (go_router) used for deep navigation
  final dynamic router;

  AgentConfig({
    this.provider = AiProviderName.gemini,
    this.apiKey,
    this.proxyUrl,
    this.proxyHeaders,
    this.model,
    this.maxSteps = 15,
    this.mcpServerMode = McpServerMode.auto,
    this.interactiveBlacklist,
    this.interactiveWhitelist,
    this.reportErrorsAsExceptions = true,
    this.gracePeriod = const Duration(milliseconds: 1500),
    this.onBeforeStep,
    this.onAfterStep,
    this.onFinish,
    this.onError,
    this.onStatusUpdate,
    this.language,
    this.instructions,
    this.systemPromptSuffix,
    this.toolInstructions,
    this.screenMap,
    this.maxTokenBudget,
    this.maxCostUsd,
    this.onBudgetWarning,
    this.enableUiControl = true,
    this.transformScreenContent,
    this.router,
  });
}

// ─── Tools & Callbacks ───────────────────────────────────────

class ToolParam {
  final String type;
  final String description;
  final List<String>? enumValues;
  final bool required;

  ToolParam({
    required this.type,
    required this.description,
    this.enumValues,
    this.required = true,
  });
}

class ToolDefinition {
  final String name;
  final String description;
  final Map<String, ToolParam> parameters;
  final Future<String> Function(Map<String, dynamic> args) handler;

  ToolDefinition({
    required this.name,
    required this.description,
    required this.parameters,
    required this.handler,
  });
}

// ─── Provider & Token Management ─────────────────────────────

class TokenUsage {
  final int promptTokens;
  final int completionTokens;
  final int totalTokens;
  final double estimatedCostUSD;

  TokenUsage({
    required this.promptTokens,
    required this.completionTokens,
    this.totalTokens = 0,
    this.estimatedCostUSD = 0.0,
  });
}

class ProviderResult {
  final String? text;
  final String? actionName;
  final Map<String, dynamic>? actionParams;
  final AgentReasoning? reasoning;
  final TokenUsage? tokenUsage;
  final Object? rawResponse;

  ProviderResult({
    this.text,
    this.actionName,
    this.actionParams,
    this.reasoning,
    this.tokenUsage,
    this.rawResponse,
  });
}

abstract class AiProvider {
  Future<ProviderResult> generateContent({
    required String systemPrompt,
    required String userMessage,
    required List<ToolDefinition> tools,
    required List<AgentStep> history,
    String? screenshotBase64,
  });
}

// ─── Actions & Zones ─────────────────────────────────────────

class ActionParameterDef {
  final String type;
  final String description;
  final List<String>? enumValues;
  final bool required;

  ActionParameterDef({
    required this.type,
    required this.description,
    this.enumValues,
    this.required = true,
  });
}

class ActionDefinition {
  final String name;
  final String description;
  final Map<String, dynamic> parameters; // String or ActionParameterDef
  final Function(Map<String, dynamic> args) handler;

  ActionDefinition({
    required this.name,
    required this.description,
    required this.parameters,
    required this.handler,
  });
}

class AiZoneConfig {
  final String id;
  final String? description;
  final bool allowSimplify;
  final bool allowGuide;
  final bool allowHighlight;

  AiZoneConfig({
    required this.id,
    this.description,
    this.allowSimplify = false,
    this.allowGuide = false,
    this.allowHighlight = true,
  });
}

class RegisteredZone {
  final AiZoneConfig config;
  final GlobalKey key;

  RegisteredZone({
    required this.config,
    required this.key,
  });
}

// ─── Chat & Knowledge ────────────────────────────────────────

class AiMessage {
  final String role; // 'user', 'assistant', 'system'
  final String content;

  AiMessage({
    required this.role,
    required this.content,
  });
}

class KnowledgeEntry {
  final String title;
  final String content;
  final List<String>? tags;
  final List<String>? screens;
  final int? priority;

  KnowledgeEntry({
    required this.title,
    required this.content,
    this.tags,
    this.screens,
    this.priority,
  });
}

abstract class KnowledgeRetriever {
  Future<List<KnowledgeEntry>> retrieve(String query, String screenName);
}

/// Dynamic alias to support both static lists and custom retrievers.
typedef KnowledgeBaseConfig = dynamic; // List<KnowledgeEntry> or KnowledgeRetriever
